name: .NET Core

on:
  push:
    paths:
      - 'Application/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'Application/**'
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

  docker:
    runs-on: ubuntu-latest

    env:
        registryName : whtscreg
        repositoryName : wth/dotnetcoreapp
        dockerFolderPath : Application/aspnet-core-dotnet-core
        tag : github.run_number

    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      uses: docker $registryName -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
    - name: Docker build
      uses: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker push
      uses: docker push $registryName/$repositoryName:$tag



