name: .NET Core

on:
  push:
    paths:
      - 'Application/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'Application/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2
    - name: Install dependencies
      run: dotnet restore Application\src\RazorPagesTestSample\RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Application\src\RazorPagesTestSample\RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal Application\src\RazorPagesTestSample\RazorPagesTestSample.csproj
